sudo: false

language: node_js

node_js:
  - 5
  # - not yet the 'stable' (node.js 6) for now bc node-sass can't handle it

install:
  - npm install

script:
  - npm run lint
  - npm run jscs
 # - npm run nsp
  - npm run cover
  - make install

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
   code_climate:
     repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - npm run codeclimate-cover-submit
  - npm run codecov-submit
