sudo: false

language: node_js

node_js:
  - "0.10"
#  - "iojs"

install:
  - npm install
  - make install

script:
  - npm run lint
  - npm run cover
  - npm run nsp

 addons:
   code_climate:
     repo_token: a958c23bd7d2a4f3685ac0687008f132ef9e835f3eaf9f15934d6b3db6057c14

after_success:
  - npm run codeclimate-cover-submit
